# =============================================================================
# Synapse Homeserver Configuration — TEMPLATE
# =============================================================================
# DO NOT EDIT THIS FILE DIRECTLY.
# This is a template processed by scripts/init-synapse.sh.
# Output: data/synapse/homeserver.yaml
#
# Variables of the form ${VARIABLE_NAME} are replaced by envsubst
# using the values in your .env file.
#
# Rules for variable substitution in YAML:
#   - String values: wrap in double quotes: "${VAR}"
#   - Boolean values: do NOT quote: ${VAR}
#   - Numeric values: do NOT quote: ${VAR}
# =============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# Core Identity
# WARNING: server_name CANNOT be changed after first deployment.
# This is your Matrix domain (appears in all user IDs: @alice:example.com).
# If you change it, all existing user accounts and room memberships break.
# ─────────────────────────────────────────────────────────────────────────────
server_name: "${MATRIX_SERVER_NAME}"
public_baseurl: "${SYNAPSE_PUBLIC_BASEURL}"
pid_file: /data/homeserver.pid

# ─────────────────────────────────────────────────────────────────────────────
# Listeners
# Synapse runs on port 8008 (plain HTTP); Traefik handles TLS termination.
# x_forwarded: true is REQUIRED when behind a reverse proxy — it tells Synapse
# to read the real client IP from the X-Forwarded-For header.
# ─────────────────────────────────────────────────────────────────────────────
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses:
      - "0.0.0.0"
    resources:
      - names:
          - client
          - federation
        compress: false

# ─────────────────────────────────────────────────────────────────────────────
# Database — PostgreSQL (required for production)
# SQLite is NOT supported in this stack.
# cp_min / cp_max: connection pool settings. Increase for high traffic.
# ─────────────────────────────────────────────────────────────────────────────
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    database: "${POSTGRES_DB}"
    host: postgres
    port: 5432
    cp_min: 5
    cp_max: 10

# ─────────────────────────────────────────────────────────────────────────────
# Redis
# Required for Synapse workers. Safe (and recommended) to include for
# single-process deployments — enables future worker migration.
# ─────────────────────────────────────────────────────────────────────────────
redis:
  enabled: true
  host: redis
  port: 6379
  password: "${REDIS_PASSWORD}"

# ─────────────────────────────────────────────────────────────────────────────
# Signing Key & Secrets
# signing_key_path: Generated by 'generate' command on first run.
# macaroon_secret_key: Used to generate access and refresh tokens.
# form_secret: Used for CSRF protection on password reset forms.
# ─────────────────────────────────────────────────────────────────────────────
signing_key_path: "/data/${MATRIX_SERVER_NAME}.signing.key"
macaroon_secret_key: "${SYNAPSE_MACAROON_SECRET_KEY}"
form_secret: "${SYNAPSE_FORM_SECRET}"

# ─────────────────────────────────────────────────────────────────────────────
# Logging
# ─────────────────────────────────────────────────────────────────────────────
log_config: "/data/log.config"

# ─────────────────────────────────────────────────────────────────────────────
# Media Store
# media_store_path: Docker volume 'synapse-media' is mounted here.
# max_upload_size: Maximum size for a single file upload.
# ─────────────────────────────────────────────────────────────────────────────
media_store_path: /data/media_store
max_upload_size: "${SYNAPSE_MAX_UPLOAD_SIZE}"
max_image_pixels: "32M"
dynamic_thumbnails: false

thumbnail_sizes:
  - width: 32
    height: 32
    method: crop
  - width: 96
    height: 96
    method: crop
  - width: 320
    height: 240
    method: scale
  - width: 640
    height: 480
    method: scale
  - width: 800
    height: 600
    method: scale

# ─────────────────────────────────────────────────────────────────────────────
# User Registration
# SECURITY: Registration is disabled by default.
# To create admin users without enabling public registration, use:
#   bash scripts/create-admin-user.sh
# which uses the registration_shared_secret.
# ─────────────────────────────────────────────────────────────────────────────
enable_registration: ${SYNAPSE_ENABLE_REGISTRATION}
registration_shared_secret: "${SYNAPSE_REGISTRATION_SHARED_SECRET}"
allow_guest_access: ${SYNAPSE_ALLOW_GUEST_ACCESS}

# Require email/phone verification before allowing registration.
# Empty list means no 3PIDs required.
registrations_require_3pid: []

# Uncomment to restrict registration to specific email domains:
# allowed_local_3pids:
#   - medium: email
#     pattern: ".*@example\\.com"

# ─────────────────────────────────────────────────────────────────────────────
# Federation
# federation_enabled: Set to false for a private, isolated homeserver.
# trusted_key_servers: Servers used to verify signing keys of remote servers.
# ─────────────────────────────────────────────────────────────────────────────
federation_enabled: ${SYNAPSE_FEDERATION_ENABLED}

trusted_key_servers:
  - server_name: "matrix.org"

suppress_key_server_warning: false

# ─────────────────────────────────────────────────────────────────────────────
# TURN / STUN — Coturn Integration
# Provides NAT traversal for WebRTC voice and video calls.
# turn_uris: The TURN URIs clients should connect to.
# turn_shared_secret: Must match COTURN_STATIC_AUTH_SECRET.
# turn_user_lifetime: Token lifetime in milliseconds (86400000 = 24 hours).
# ─────────────────────────────────────────────────────────────────────────────
turn_uris:
  - "turn:${COTURN_REALM}:${COTURN_PORT}?transport=udp"
  - "turn:${COTURN_REALM}:${COTURN_PORT}?transport=tcp"
  - "turns:${COTURN_REALM}:${COTURN_TLS_PORT}?transport=tcp"
turn_shared_secret: "${COTURN_STATIC_AUTH_SECRET}"
turn_user_lifetime: 86400000
turn_allow_guests: false

# ─────────────────────────────────────────────────────────────────────────────
# Rate Limiting
# These are conservative defaults suitable for a small to medium homeserver.
# Increase burst_count and per_second for larger deployments.
# ─────────────────────────────────────────────────────────────────────────────
rc_message:
  per_second: 0.2
  burst_count: 10

rc_registration:
  per_second: 0.17
  burst_count: 3

rc_login:
  address:
    per_second: 0.17
    burst_count: 3
  account:
    per_second: 0.17
    burst_count: 3
  failed_attempts:
    per_second: 0.17
    burst_count: 3

rc_admin_redaction:
  per_second: 1
  burst_count: 50

rc_joins:
  local:
    per_second: 0.1
    burst_count: 10
  remote:
    per_second: 0.01
    burst_count: 10

rc_federation:
  window_size: 1000
  sleep_limit: 10
  sleep_delay: 500
  reject_limit: 50
  concurrent: 3

# ─────────────────────────────────────────────────────────────────────────────
# Push Notifications
# include_content: false avoids sending message content in push notifications
# (privacy-preserving default).
# ─────────────────────────────────────────────────────────────────────────────
push:
  include_content: false
  group_unread_count_by_room: false

# ─────────────────────────────────────────────────────────────────────────────
# Room Settings
# default_room_version: Room version 10 is the current stable version.
# encrypted_by_default: 'invite' means rooms with invites are encrypted by default.
# ─────────────────────────────────────────────────────────────────────────────
default_room_version: "10"
encrypted_by_default: invite

# ─────────────────────────────────────────────────────────────────────────────
# URL Previews
# Disabled by default. When enabled, Synapse fetches URLs on behalf of clients
# which can leak server IP or cause SSRF if not properly configured.
# ─────────────────────────────────────────────────────────────────────────────
url_preview_enabled: false
# To enable, set url_preview_enabled: true and configure the blacklist:
# url_preview_ip_range_blacklist:
#   - '127.0.0.0/8'
#   - '10.0.0.0/8'
#   - '172.16.0.0/12'
#   - '192.168.0.0/16'
#   - '100.64.0.0/10'
#   - '169.254.0.0/16'
#   - '::1/128'
#   - 'fe80::/64'
#   - 'fc00::/7'

# ─────────────────────────────────────────────────────────────────────────────
# Message Retention
# Disabled by default. When enabled, Synapse will purge old events from rooms
# that have a retention policy set.
# ─────────────────────────────────────────────────────────────────────────────
retention:
  enabled: false
  # Uncomment to set a server-wide default retention policy:
  # default_policy:
  #   min_lifetime: 1d
  #   max_lifetime: 1y

# ─────────────────────────────────────────────────────────────────────────────
# Metrics — Prometheus
# Disabled by default. To enable:
#   1. Set enable_metrics: true
#   2. Add a metrics listener (see commented example below)
#   3. Configure Prometheus to scrape port 9090
# ─────────────────────────────────────────────────────────────────────────────
enable_metrics: false
# When enabled, add this to the listeners section:
# - port: 9090
#   type: metrics
#   bind_addresses:
#     - '0.0.0.0'

# ─────────────────────────────────────────────────────────────────────────────
# Telemetry
# Disabled. Synapse would otherwise report anonymous usage statistics.
# ─────────────────────────────────────────────────────────────────────────────
report_stats: false

# ─────────────────────────────────────────────────────────────────────────────
# Email Configuration
# Disabled by default. Set MATRIX_EMAIL_ENABLED=true in .env and
# uncomment the section below to enable email notifications and verification.
# ─────────────────────────────────────────────────────────────────────────────
# email:
#   smtp_host: "${SMTP_HOST}"
#   smtp_port: ${SMTP_PORT}
#   smtp_user: "${SMTP_USER}"
#   smtp_pass: "${SMTP_PASSWORD}"
#   require_transport_security: true
#   enable_tls: true
#   notif_from: "${EMAIL_NOTIF_FROM}"
#   app_name: "Matrix"
#   enable_notifs: true
#   notif_delay_before_mail: 10m
#   invite_client_location: "https://${ELEMENT_HOSTNAME}"

# ─────────────────────────────────────────────────────────────────────────────
# OIDC / Single Sign-On (stub — not configured)
# Uncomment and fill in your IdP details to enable SSO.
# See docs/SECURITY.md for full OIDC configuration instructions.
# ─────────────────────────────────────────────────────────────────────────────
# oidc_providers:
#   - idp_id: your_idp
#     idp_name: "Your Identity Provider"
#     issuer: "https://sso.example.com/realms/master"
#     client_id: "matrix"
#     client_secret: "your-oidc-client-secret"
#     scopes: ["openid", "profile", "email"]
#     user_mapping_provider:
#       config:
#         localpart_template: "{{ user.preferred_username }}"
#         display_name_template: "{{ user.name }}"
#         email_template: "{{ user.email }}"

# ─────────────────────────────────────────────────────────────────────────────
# Spam Checking (optional module)
# ─────────────────────────────────────────────────────────────────────────────
# spam_checker:
#   - module: "your_spam_checker_module.SpamChecker"
#     config: {}

# ─────────────────────────────────────────────────────────────────────────────
# Server Notices (optional)
# A special room used to send notices to all users on the homeserver.
# ─────────────────────────────────────────────────────────────────────────────
# server_notices:
#   system_mxid_localpart: notices
#   system_mxid_display_name: "Server Notices"
#   room_name: "Server Notices"

# ─────────────────────────────────────────────────────────────────────────────
# Experimental Features
# ─────────────────────────────────────────────────────────────────────────────
experimental_features:
  # MSC3575 (Sliding Sync) — needed for Element X and next-generation clients.
  # Set to true if you want to support Element X.
  msc3575_enabled: false
